import json
import re
import sys
import time
import requests

from pathlib import Path
from typing import Dict, List, Any


# ============================================================
# CONFIGURATION
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/generate"

MODEL_NAME = "mistral"

BASE_DIR = Path(__file__).resolve().parents[2]

PROCESSED_DIR = BASE_DIR / "Input_Data" / "processed"

OUTPUT_DIR = BASE_DIR / "Input_Data" / "processed"

# Keep batches small because local Ollama/Mistral can become
# very slow with large PDF contexts.
PAGES_PER_BATCH = 2

# Maximum amount of text sent from one page.
MAX_PAGE_CHARS = 7000

# Maximum approximate context sent to one LLM call.
MAX_BATCH_CHARS = 12000

# Ollama timeout.
OLLAMA_TIMEOUT = 300

# Retry count for temporary Ollama failures.
OLLAMA_RETRIES = 1


# ============================================================
# COMMON UTILITIES
# ============================================================

def clean_text(text: str) -> str:
    """
    Clean PDF extracted text while preserving technical terms.
    """

    if not text:
        return ""

    text = text.replace("\x00", " ")

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


def truncate_text(
    text: str,
    max_chars: int = MAX_PAGE_CHARS
) -> str:
    """
    Prevent extremely large PDF pages from creating
    unnecessarily large LLM prompts.
    """

    text = clean_text(text)

    if len(text) <= max_chars:
        return text

    return text[:max_chars] + " ..."


def load_processed_document(
    json_path: str
) -> Dict[str, Any]:
    """
    Load the processed PDF JSON generated by the
    PDF ingestion checkpoint.
    """

    path = Path(json_path)

    if not path.exists():
        raise FileNotFoundError(
            f"Processed JSON not found: {json_path}"
        )

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)


def save_json(
    data: Dict[str, Any],
    output_path: str
):
    """
    Save architecture extraction result.
    """

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            data,
            f,
            indent=2,
            ensure_ascii=False
        )


# ============================================================
# OLLAMA
# ============================================================

def call_ollama(
    prompt: str
) -> str:
    """
    Send a prompt to the local Ollama Mistral model.

    JSON mode is used to reduce malformed responses.
    """

    payload = {

        "model": MODEL_NAME,

        "prompt": prompt,

        "stream": False,

        "format": "json",

        "options": {

            "temperature": 0,

            # Limit generation length.
            "num_predict": 700,

            # Keep model context manageable.
            "num_ctx": 4096
        }
    }

    last_error = None

    for attempt in range(
        OLLAMA_RETRIES + 1
    ):

        try:

            response = requests.post(
                OLLAMA_URL,
                json=payload,
                timeout=OLLAMA_TIMEOUT
            )

            response.raise_for_status()

            result = response.json()

            return result.get(
                "response",
                ""
            )

        except (
            requests.exceptions.Timeout,
            requests.exceptions.ConnectionError
        ) as exc:

            last_error = exc

            print(
                f"    Ollama attempt "
                f"{attempt + 1}/"
                f"{OLLAMA_RETRIES + 1} failed: "
                f"{exc}"
            )

            if attempt < OLLAMA_RETRIES:

                print(
                    "    Retrying..."
                )

                time.sleep(2)

    raise RuntimeError(
        f"Ollama request failed after "
        f"{OLLAMA_RETRIES + 1} attempts: "
        f"{last_error}"
    )


# ============================================================
# JSON PARSER
# ============================================================

def extract_json(
    response: str
) -> Dict[str, Any]:
    """
    Convert the LLM response into a Python dictionary.
    """

    if not response:
        raise ValueError(
            "Empty response received from Ollama."
        )

    response = response.strip()

    # Remove markdown fences if present.
    response = re.sub(
        r"```json\s*",
        "",
        response,
        flags=re.IGNORECASE
    )

    response = re.sub(
        r"```\s*",
        "",
        response
    )

    # Find JSON object.
    start = response.find("{")

    end = response.rfind("}")

    if start == -1 or end == -1:

        raise ValueError(
            "No JSON object found in Ollama response."
        )

    json_text = response[
        start:end + 1
    ]

    try:

        result = json.loads(
            json_text
        )

    except json.JSONDecodeError as exc:

        raise ValueError(
            f"Invalid JSON returned by Ollama: {exc}"
        )

    if not isinstance(
        result,
        dict
    ):

        raise ValueError(
            "Ollama JSON response is not an object."
        )

    return result


# ============================================================
# PAGE ROUTING
# ============================================================

class AgentPageRouter:
    """
    Routes only relevant PDF pages to each specialized agent.

    This is the main improvement over the previous design.

    Instead of:

        171 pages × 6 agents

    we do:

        relevant pages → relevant agent
    """

    KEYWORDS = {

        "component": [

            "software component",

            "software components",

            "sw-c",

            "swc",

            "basic software",

            "bsw",

            "bsw module",

            "software module",

            "component",

            "rte",

            "runtime environment",

            "application layer",

            "service layer",

            "ecu abstraction"
        ],

        "interface": [

            "interface",

            "interfaces",

            "portinterface",

            "port interface",

            "senderreceiverinterface",

            "sender-receiver interface",

            "clientserverinterface",

            "client-server interface",

            "s/r interface",

            "service interface",

            "client/server interface"
        ],

        "port": [

            "p-port",

            "r-port",

            "pport",

            "rport",

            "provided port",

            "required port",

            "port prototype",

            "provide port",

            "require port"
        ],

        "signal": [

            "signal",

            "signals",

            "i-signal",

            "i-signal-group",

            "signal group",

            "i-pdu",

            "i-pdus",

            "pdu",
            
            "pdus"
        ],

        "runnable": [

            "runnable",

            "runnables",

            "runnableentity",

            "runnable entity",

            "runnable entities"
        ],

        "relationship": [

            "provides",

            "provided",

            "requires",

            "required",

            "uses",

            "communicates",

            "communication",

            "depends on",

            "dependent",

            "connected to",

            "connects",

            "interaction",

            "interacts",

            "relationship",

            "relations",
            
            "mapping",

            "mapped to"
        ]
    }

    @classmethod
    def route(
        cls,
        pages: List[Dict[str, Any]],
        agent_type: str
    ) -> List[Dict[str, Any]]:
        """
        Select pages relevant to a particular agent.
        """

        keywords = cls.KEYWORDS.get(
            agent_type,
            []
        )

        selected_pages = []

        for page in pages:

            text = clean_text(
                page.get(
                    "text",
                    ""
                )
            ).lower()

            if not text:
                continue

            matched = False

            for keyword in keywords:

                if keyword in text:

                    matched = True

                    break

            if matched:

                selected_pages.append(
                    page
                )

        return selected_pages


# ============================================================
# PAGE BATCHING
# ============================================================

def create_page_batches(
    pages: List[Dict[str, Any]]
) -> List[List[Dict[str, Any]]]:
    """
    Split selected pages into small batches.
    """

    batches = []

    current_batch = []

    current_chars = 0

    for page in pages:

        page_text = truncate_text(
            page.get(
                "text",
                ""
            )
        )

        estimated_size = len(
            page_text
        )

        # Start a new batch when the current batch is full.
        if (
            current_batch
            and
            (
                len(current_batch)
                >= PAGES_PER_BATCH
                or
                current_chars + estimated_size
                > MAX_BATCH_CHARS
            )
        ):

            batches.append(
                current_batch
            )

            current_batch = []

            current_chars = 0

        current_batch.append(
            page
        )

        current_chars += estimated_size

    if current_batch:

        batches.append(
            current_batch
        )

    return batches


# ============================================================
# PAGE FORMATTER
# ============================================================

def format_pages(
    batch: List[Dict[str, Any]]
) -> str:
    """
    Convert PDF pages into structured LLM context.
    """

    output = []

    for page in batch:

        page_number = page.get(
            "page_number",
            "unknown"
        )

        section = page.get(
            "section",
            ""
        )

        text = truncate_text(
            page.get(
                "text",
                ""
            )
        )

        output.append(

            f"""
--- PAGE {page_number} ---

SECTION:
{section}

TEXT:
{text}
"""
        )

    return "\n".join(
        output
    )


# ============================================================
# BASE EXTRACTION AGENT
# ============================================================

class ExtractionAgent:
    """
    Base class for specialized AUTOSAR extraction agents.
    """

    def __init__(
        self,
        name: str,
        entity_type: str,
        instructions: str
    ):

        self.name = name

        self.entity_type = entity_type

        self.instructions = instructions

    def build_prompt(
        self,
        page_context: str
    ) -> str:

        return f"""
You are the {self.name} in a specialized
AUTOSAR architecture analysis system.

Your ONLY task is:

{self.entity_type}

You are one specialized agent in a multi-agent system.

Do NOT perform the tasks of other agents.

============================================================
GENERAL RULES
============================================================

1. Extract ONLY information explicitly supported by
   the supplied document.

2. Do NOT invent entities.

3. Do NOT use outside AUTOSAR knowledge to create
   missing names.

4. Preserve technical names exactly as they appear.

5. Every extracted entity must contain evidence.

6. Every extracted entity must contain its source page.

7. If no valid entity exists, return:

{{
    "entities": []
}}

8. Ignore ordinary English words.

9. Do not turn descriptive phrases into entity names.

10. Do not extract an entity simply because a keyword
    appears nearby.

11. Avoid duplicate entities within the same page.

12. Return JSON ONLY.

============================================================
SPECIALIZED AGENT RULES
============================================================

{self.instructions}

============================================================
OUTPUT FORMAT
============================================================

Return:

{{
    "entities": [
        {{
            "name": "exact technical name",
            "type": "{self.entity_type}",
            "page": 0,
            "section": "section name",
            "evidence": "short supporting evidence"
        }}
    ]
}}

============================================================
DOCUMENT CONTEXT
============================================================

{page_context}
"""

    def extract_from_batch(
        self,
        batch: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        page_context = format_pages(
            batch
        )

        prompt = self.build_prompt(
            page_context
        )

        try:

            response = call_ollama(
                prompt
            )

            result = extract_json(
                response
            )

            entities = result.get(
                "entities",
                []
            )

            if not isinstance(
                entities,
                list
            ):

                return []

            return self.validate_results(
                entities,
                batch
            )

        except Exception as exc:

            print(
                f"    [{self.name}] "
                f"Batch failed: {exc}"
            )

            return []

    @staticmethod
    def validate_results(
        entities: List[Dict[str, Any]],
        batch: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        valid_pages = set()

        for page in batch:

            valid_pages.add(
                str(
                    page.get(
                        "page_number"
                    )
                )
            )

        validated = []

        for item in entities:

            if not isinstance(
                item,
                dict
            ):

                continue

            name = str(
                item.get(
                    "name",
                    ""
                )
            ).strip()

            if not name:
                continue

            page = item.get(
                "page"
            )

            # Keep only pages actually supplied to the agent.
            if page is not None:

                if str(page) not in valid_pages:

                    continue

            evidence = str(
                item.get(
                    "evidence",
                    ""
                )
            ).strip()

            if not evidence:
                continue

            item["name"] = name

            item["evidence"] = evidence

            validated.append(
                item
            )

        return validated


# ============================================================
# COMPONENT AGENT
# ============================================================

class ComponentAgent(
    ExtractionAgent
):

    def __init__(self):

        super().__init__(

            name=
                "AUTOSAR Component Extraction Agent",

            entity_type=
                "AUTOSAR software and BSW components",

            instructions="""
Extract only explicit AUTOSAR architectural components.

Examples include:

- Application Software Component
- SW-C
- Software Component
- RTE
- BSW
- BSW Module
- AUTOSAR OS
- COM
- NvM
- PduR
- CanIf
- CanTp
- TcpIp
- SoAd
- Dlt
- EcuM
- Dem
- ComM
- StbM
- WdgM

A component must be explicitly presented as a software
component, BSW module, AUTOSAR module, layer component,
or architectural component.

Do NOT extract:

- data
- functionality
- communication
- transformer
- service
- API
- interface
- event
- signal

unless the document explicitly identifies that term
as an architectural component.
"""
        )


# ============================================================
# INTERFACE AGENT
# ============================================================

class InterfaceAgent(
    ExtractionAgent
):

    def __init__(self):

        super().__init__(

            name=
                "AUTOSAR Interface Extraction Agent",

            entity_type=
                "AUTOSAR interfaces and interface types",

            instructions="""
Extract explicitly identified AUTOSAR interfaces.

Look for:

- AUTOSAR Interface
- PortInterface
- SenderReceiverInterface
- ClientServerInterface
- Service Interface
- S/R Interface
- Client/Server Interface
- Sender/Receiver Interface

Important:

The following are NOT automatically interface names:

- Data Elements
- Events
- Ports
- Signals
- Services
- Communication
- Information

Example:

"Service Interface - Events"

Correct:

Service Interface

Incorrect:

Events

Example:

"S/R Interface - Data Elements"

Correct:

S/R Interface

Incorrect:

Data Elements

If a named interface appears, preserve the exact name.

Do not create an interface from the word "interface"
alone when it is being used as ordinary English.
"""
        )


# ============================================================
# PORT AGENT
# ============================================================

class PortAgent(
    ExtractionAgent
):

    def __init__(self):

        super().__init__(

            name=
                "AUTOSAR Port Extraction Agent",

            entity_type=
                "AUTOSAR ports and port prototypes",

            instructions="""
Extract explicit AUTOSAR ports.

Look for:

- P-Port
- R-Port
- P-Port Prototype
- R-Port Prototype
- Provided Port
- Required Port
- Port Prototype

A generic occurrence of "port" is NOT enough.

The surrounding document must explicitly identify
the item as an AUTOSAR architectural port.

If a port has a name, preserve the complete name.

Do not extract:

- port
- ports
- incoming
- outgoing
- provided
- required

as port names unless they are part of an explicit
architectural port declaration.
"""
        )


# ============================================================
# SIGNAL AGENT
# ============================================================

class SignalAgent(
    ExtractionAgent
):

    def __init__(self):

        super().__init__(

            name=
                "AUTOSAR Signal Extraction Agent",

            entity_type=
                "AUTOSAR signals, signal groups and I-PDUs",

            instructions="""
Extract only explicitly identified signal-related
AUTOSAR entities.

Look for:

- Signal
- I-Signal
- I-Signal Group
- Signal Group
- I-PDU
- I-PDU Group
- named signals in an explicit signal definition
- named signals in an explicit signal communication
  context

Do NOT extract generic words:

- data
- service
- functionality
- events
- groups
- bytes
- payload
- communication

unless the document clearly identifies them as a
signal-related architectural entity.

Preserve exact technical names.
"""
        )


# ============================================================
# RUNNABLE AGENT
# ============================================================

class RunnableAgent(
    ExtractionAgent
):

    def __init__(self):

        super().__init__(

            name=
                "AUTOSAR Runnable Extraction Agent",

            entity_type=
                "AUTOSAR runnable entities",

            instructions="""
Extract only explicitly identified AUTOSAR runnables.

Look for:

- RunnableEntity
- Runnable Entity
- Runnable
- Runnable Entities
- named functions explicitly described as runnables

Do NOT treat every function or API as a runnable.

For example:

"API"
"MainFunction"
"function"
"method"

must not automatically become a runnable.

The document must explicitly establish the runnable
meaning.
"""
        )


# ============================================================
# RELATIONSHIP AGENT
# ============================================================

class RelationshipAgent(
    ExtractionAgent
):

    def __init__(self):

        super().__init__(

            name=
                "AUTOSAR Relationship Extraction Agent",

            entity_type=
                "relationships between AUTOSAR architectural entities",

            instructions="""
Extract explicit relationships between meaningful
AUTOSAR architectural entities.

Valid relationship examples:

Component A provides Interface B.

Component A requires Interface B.

Component A uses Component B.

Component A communicates with Component B.

Component A depends on Component B.

Component A contains Component B.

Component A is connected to Component B.

Component A provides Service B.

The source and target should be meaningful
architectural entities.

Do NOT extract ordinary English phrases such as:

"provides a generic API"

"requires a description"

"uses the mechanism"

"provides functionality"

"requires the data"

"provides synchronized time"

unless the source and target themselves are
clearly identifiable architectural entities.

Return each relationship as:

{
    "source": "...",
    "relation": "...",
    "target": "...",
    "page": 0,
    "section": "...",
    "evidence": "..."
}

The relation should be concise, such as:

provides
requires
uses
communicates_with
depends_on
contains
connected_to
maps_to
"""
        )

    def build_prompt(
        self,
        page_context: str
    ) -> str:

        return f"""
You are the AUTOSAR Relationship Extraction Agent.

Your ONLY task is to extract explicit architectural
relationships.

============================================================
RULES
============================================================

1. Both source and target must be meaningful
   architectural entities.

2. Do not extract ordinary English grammar.

3. Do not extract relationships from generic phrases.

4. Do not invent source or target names.

5. Use only the supplied document.

6. Preserve exact entity names.

7. Every relationship must have evidence.

8. Every relationship must have a page.

9. Return JSON ONLY.

============================================================
VALID RELATION TYPES
============================================================

provides
requires
uses
communicates_with
depends_on
contains
connected_to
maps_to

============================================================
INVALID EXAMPLES
============================================================

WRONG:

"Transformer" -> "generic API"

WRONG:

"system" -> "functionality"

WRONG:

"module" -> "description"

WRONG:

"component" -> "data"

============================================================
OUTPUT FORMAT
============================================================

{{
    "relationships": [
        {{
            "source": "AUTOSAR entity",
            "relation": "provides",
            "target": "AUTOSAR entity",
            "page": 0,
            "section": "section",
            "evidence": "short supporting evidence"
        }}
    ]
}}

If no valid relationship exists:

{{
    "relationships": []
}}

============================================================
DOCUMENT CONTEXT
============================================================

{page_context}
"""

    def extract_from_batch(
        self,
        batch: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        page_context = format_pages(
            batch
        )

        prompt = self.build_prompt(
            page_context
        )

        try:

            response = call_ollama(
                prompt
            )

            result = extract_json(
                response
            )

            relationships = result.get(
                "relationships",
                []
            )

            if not isinstance(
                relationships,
                list
            ):

                return []

            return self.validate_relationships(
                relationships,
                batch
            )

        except Exception as exc:

            print(
                f"    [{self.name}] "
                f"Batch failed: {exc}"
            )

            return []

    @staticmethod
    def validate_relationships(
        relationships: List[Dict[str, Any]],
        batch: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        valid_pages = {

            str(
                page.get(
                    "page_number"
                )
            )

            for page in batch
        }

        valid = []

        for item in relationships:

            if not isinstance(
                item,
                dict
            ):

                continue

            source = str(
                item.get(
                    "source",
                    ""
                )
            ).strip()

            relation = str(
                item.get(
                    "relation",
                    ""
                )
            ).strip()

            target = str(
                item.get(
                    "target",
                    ""
                )
            ).strip()

            evidence = str(
                item.get(
                    "evidence",
                    ""
                )
            ).strip()

            if not source:
                continue

            if not relation:
                continue

            if not target:
                continue

            if not evidence:
                continue

            page = item.get(
                "page"
            )

            if page is not None:

                if str(page) not in valid_pages:

                    continue

            valid.append({

                "source": source,

                "relation": relation,

                "target": target,

                "page": page,

                "section": item.get(
                    "section",
                    ""
                ),

                "evidence": evidence
            })

        return valid


# ============================================================
# AGENT MANAGER
# ============================================================

class ArchitectureAgentManager:
    """
    Coordinates the specialized extraction agents.
    """

    AGENT_TYPES = {

        "AUTOSAR Component Extraction Agent":
            "component",

        "AUTOSAR Interface Extraction Agent":
            "interface",

        "AUTOSAR Port Extraction Agent":
            "port",

        "AUTOSAR Signal Extraction Agent":
            "signal",

        "AUTOSAR Runnable Extraction Agent":
            "runnable",

        "AUTOSAR Relationship Extraction Agent":
            "relationship"
    }

    RESULT_KEYS = {

        "component":
            "components",

        "interface":
            "interfaces",

        "port":
            "ports",

        "signal":
            "signals",

        "runnable":
            "runnables",

        "relationship":
            "relationships"
    }

    def __init__(self):

        self.agents = [

            ComponentAgent(),

            InterfaceAgent(),

            PortAgent(),

            SignalAgent(),

            RunnableAgent(),

            RelationshipAgent()
        ]

    def run(
        self,
        pages: List[Dict[str, Any]]
    ) -> Dict[str, Any]:

        final_result = {

            "components": [],

            "interfaces": [],

            "ports": [],

            "signals": [],

            "runnables": [],

            "relationships": []
        }

        print()
        print(
            "=" * 70
        )

        print(
            "AUTOSAR MULTI-AGENT ARCHITECTURE EXTRACTION"
        )

        print(
            "=" * 70
        )

        print(
            f"Total document pages : {len(pages)}"
        )

        print(
            f"Specialized agents   : {len(self.agents)}"
        )

        print(
            f"Pages per batch      : {PAGES_PER_BATCH}"
        )

        print(
            f"Max batch context    : {MAX_BATCH_CHARS}"
        )

        print(
            "=" * 70
        )

        # ----------------------------------------------------
        # RUN EACH SPECIALIZED AGENT
        # ----------------------------------------------------

        for agent in self.agents:

            agent_name = agent.name

            agent_type = self.AGENT_TYPES[
                agent_name
            ]

            result_key = self.RESULT_KEYS[
                agent_type
            ]

            print()
            print(
                "-" * 70
            )

            print(
                f"[AGENT] {agent_name}"
            )

            # ------------------------------------------------
            # ROUTE RELEVANT PAGES
            # ------------------------------------------------

            selected_pages = (
                AgentPageRouter.route(
                    pages,
                    agent_type
                )
            )

            print(
                f"  Relevant pages: "
                f"{len(selected_pages)} / "
                f"{len(pages)}"
            )

            if not selected_pages:

                print(
                    "  No relevant pages found."
                )

                continue

            # ------------------------------------------------
            # CREATE BATCHES
            # ------------------------------------------------

            batches = create_page_batches(
                selected_pages
            )

            print(
                f"  Batches: {len(batches)}"
            )

            agent_results = []

            # ------------------------------------------------
            # PROCESS BATCHES
            # ------------------------------------------------

            for batch_number, batch in enumerate(
                batches,
                start=1
            ):

                page_numbers = [

                    str(
                        page.get(
                            "page_number",
                            "?"
                        )
                    )

                    for page in batch
                ]

                print(
                    f"  Batch "
                    f"{batch_number}/"
                    f"{len(batches)} "
                    f"pages={page_numbers}"
                )

                results = (
                    agent.extract_from_batch(
                        batch
                    )
                )

                agent_results.extend(
                    results
                )

            # ------------------------------------------------
            # DEDUPLICATE
            # ------------------------------------------------

            if agent_type == "relationship":

                cleaned = (
                    self.deduplicate_relationships(
                        agent_results
                    )
                )

            else:

                cleaned = (
                    self.deduplicate_entities(
                        agent_results
                    )
                )

            final_result[
                result_key
            ] = cleaned

            print(
                f"  Final extracted: "
                f"{len(cleaned)}"
            )

        return final_result

    # ========================================================
    # ENTITY DEDUPLICATION
    # ========================================================

    @staticmethod
    def deduplicate_entities(
        items: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        unique = {}

        for item in items:

            if not isinstance(
                item,
                dict
            ):

                continue

            name = str(
                item.get(
                    "name",
                    ""
                )
            ).strip()

            if not name:

                continue

            # Same entity on different pages should be
            # consolidated by name.
            key = name.lower()

            if key not in unique:

                unique[key] = {

                    "name": name,

                    "type": item.get(
                        "type",
                        ""
                    ),

                    "page": item.get(
                        "page"
                    ),

                    "section": item.get(
                        "section",
                        ""
                    ),

                    "evidence": item.get(
                        "evidence",
                        ""
                    ),

                    "evidence_locations": []
                }

            page = item.get(
                "page"
            )

            evidence = item.get(
                "evidence",
                ""
            )

            location = {

                "page": page,

                "section": item.get(
                    "section",
                    ""
                ),

                "evidence": evidence
            }

            existing_locations = unique[
                key
            ][
                "evidence_locations"
            ]

            # Avoid duplicate evidence locations.
            already_exists = any(

                loc.get("page") == page
                and
                loc.get("evidence") == evidence

                for loc in existing_locations
            )

            if not already_exists:

                existing_locations.append(
                    location
                )

        return list(
            unique.values()
        )

    # ========================================================
    # RELATIONSHIP DEDUPLICATION
    # ========================================================

    @staticmethod
    def deduplicate_relationships(
        items: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        unique = {}

        for item in items:

            if not isinstance(
                item,
                dict
            ):

                continue

            source = str(
                item.get(
                    "source",
                    ""
                )
            ).strip()

            relation = str(
                item.get(
                    "relation",
                    ""
                )
            ).strip()

            target = str(
                item.get(
                    "target",
                    ""
                )
            ).strip()

            if not source:
                continue

            if not relation:
                continue

            if not target:
                continue

            key = (

                source.lower(),

                relation.lower(),

                target.lower()
            )

            if key not in unique:

                unique[key] = {

                    "source": source,

                    "relation": relation,

                    "target": target,

                    "page": item.get(
                        "page"
                    ),

                    "section": item.get(
                        "section",
                        ""
                    ),

                    "evidence": item.get(
                        "evidence",
                        ""
                    ),

                    "evidence_locations": []
                }

            location = {

                "page": item.get(
                    "page"
                ),

                "section": item.get(
                    "section",
                    ""
                ),

                "evidence": item.get(
                    "evidence",
                    ""
                )
            }

            existing = unique[
                key
            ][
                "evidence_locations"
            ]

            already_exists = any(

                loc.get("page")
                ==
                location.get("page")

                and

                loc.get("evidence")
                ==
                location.get("evidence")

                for loc in existing
            )

            if not already_exists:

                existing.append(
                    location
                )

        return list(
            unique.values()
        )


# ============================================================
# FINAL ARCHITECTURE EXTRACTION
# ============================================================

def extract_architecture(
    processed_json_path: str
) -> Dict[str, Any]:
    """
    Execute the complete multi-agent extraction pipeline.
    """

    document = load_processed_document(
        processed_json_path
    )

    pages = document.get(
        "pages",
        []
    )

    if not pages:

        raise ValueError(
            "No pages found in processed document."
        )

    manager = (
        ArchitectureAgentManager()
    )

    extracted = manager.run(
        pages
    )

    # --------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------

    result = {

        "document_id":
            document.get(
                "document_id"
            ),

        "document_name":
            document.get(
                "document_name"
            ),

        "extraction_method":
            "multi_agent_llm",

        "model":
            MODEL_NAME,

        "architecture_extraction_agents": [

            {
                "agent":
                    "component_agent",

                "responsibility":
                    "Extract AUTOSAR software and BSW components"
            },

            {
                "agent":
                    "interface_agent",

                "responsibility":
                    "Extract AUTOSAR interfaces"
            },

            {
                "agent":
                    "port_agent",

                "responsibility":
                    "Extract AUTOSAR ports and port prototypes"
            },

            {
                "agent":
                    "signal_agent",

                "responsibility":
                    "Extract signals, signal groups and I-PDUs"
            },

            {
                "agent":
                    "runnable_agent",

                "responsibility":
                    "Extract runnable entities"
            },

            {
                "agent":
                    "relationship_agent",

                "responsibility":
                    "Extract architectural relationships"
            }
        ],

        "entities": extracted,

        "statistics": {

            "components":
                len(
                    extracted[
                        "components"
                    ]
                ),

            "interfaces":
                len(
                    extracted[
                        "interfaces"
                    ]
                ),

            "ports":
                len(
                    extracted[
                        "ports"
                    ]
                ),

            "signals":
                len(
                    extracted[
                        "signals"
                    ]
                ),

            "runnables":
                len(
                    extracted[
                        "runnables"
                    ]
                ),

            "relationships":
                len(
                    extracted[
                        "relationships"
                    ]
                ),

            "pages_processed":
                len(pages)
        }
    }

    return result


# ============================================================
# COMMAND LINE ENTRY
# ============================================================

if __name__ == "__main__":

    if len(sys.argv) < 2:

        print()

        print(
            "Usage:"
        )

        print()

        print(
            "python "
            "Code/ingestion/"
            "agentic_architecture_extractor.py "
            "\"Input_Data/processed/<document>.json\""
        )

        print()

        sys.exit(1)

    input_file = sys.argv[1]

    print()

    print(
        f"Input: {input_file}"
    )

    print()

    try:

        result = extract_architecture(
            input_file
        )

        document_id = result.get(
            "document_id",
            "architecture"
        )

        output_file = (

            OUTPUT_DIR /

            f"{document_id}"
            "_agentic_architecture.json"
        )

        save_json(
            result,
            output_file
        )

        print()
        print(
            "=" * 70
        )

        print(
            "EXTRACTION COMPLETE"
        )

        print(
            "=" * 70
        )

        print()

        print(
            json.dumps(
                result[
                    "statistics"
                ],
                indent=2
            )
        )

        print()

        print(
            f"Output: {output_file}"
        )

        print()

    except Exception as exc:

        print()

        print(
            "=" * 70
        )

        print(
            "EXTRACTION FAILED"
        )

        print(
            "=" * 70
        )

        print()

        print(
            str(exc)
        )

        print()

        sys.exit(1)